<?php if($block->getQuoteId()): ?>
    <div class="loading-mask" data-role="loader"><div class="loader"><img alt="Loading..." src="<?php echo $this->getViewFileUrl('PaysonAB_PaysonCheckout2::images/loader-2.gif'); ?>"></div></div>
<script type="text/javascript">
        require([
            'jquery',
            'mage/url',
        ], function ($, url) {
            'use strict';
            var returnURl = url.build('returns')
            setTimeout(function(){
            $.ajax({
                    url: returnURl, //url.build('returns'),
                type:'POST',
                dataType:'json',
                success:function(response){
                    if (response.redirectUrl) {
                        window.location.href = response.redirectUrl;
                    }
                }
            });
            }, 3000);



        });
    </script>
<?php endif; ?>
