<?php if($block->getQuoteId()): ?>
    <div class="loading-mask" data-role="loader"><div class="loader"><img alt="Loading..." src="<?php echo $this->getViewFileUrl('Eastlane_PaysonCheckout2::images/loader-2.gif'); ?>"></div></div>
    <script type="text/javascript">
        require([
            'jquery',
            'mage/url',
        ], function ($, url) {
            'use strict';
            var url =  url.build('cancel?id=<?php echo $block->getQuoteId() ?>')
            $.ajax({
                url: url,
                type:'POST',
                dataType:'json',
                success:function(response){
                    if (response.redirectUrl) {
                        window.location.href = response.redirectUrl;
                    }
                }
            });
        });
    </script>
<?php endif; ?>
